[package]
name = "cmake_forge"
version = "0.2.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive", "cargo"] }
